2025-05-28 22:16:41,503 - kedro.framework.project - INFO - Using 'conf/logging.yml' as logging configuration. You can change this by setting the KEDRO_LOGGING_CONFIG environment variable accordingly.
2025-05-28 22:16:41,550 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/kedro/io/data_catalog.py:165: KedroDeprecationWarning: `DataCatalog` has been deprecated and will be replaced by `KedroDataCatalog`, in Kedro 1.0.0.Currently some `KedroDataCatalog` APIs have been retained for compatibility with `DataCatalog`, including the `datasets` property and the `get_datasets`, `_get_datasets`, `add`,` list`, `add_feed_dict`, and `shallow_copy` methods. These will be removed or replaced with updated alternatives in Kedro 1.0.0. For more details, refer to the documentation: https://docs.kedro.org/en/stable/data/index.html#kedrodatacatalog-experimental-feature
  warnings.warn(

2025-05-28 22:16:41,611 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/kedro/io/data_catalog.py:165: KedroDeprecationWarning: `DataCatalog` has been deprecated and will be replaced by `KedroDataCatalog`, in Kedro 1.0.0.Currently some `KedroDataCatalog` APIs have been retained for compatibility with `DataCatalog`, including the `datasets` property and the `get_datasets`, `_get_datasets`, `add`,` list`, `add_feed_dict`, and `shallow_copy` methods. These will be removed or replaced with updated alternatives in Kedro 1.0.0. For more details, refer to the documentation: https://docs.kedro.org/en/stable/data/index.html#kedrodatacatalog-experimental-feature
  warnings.warn(

2025-05-28 22:16:41,621 - kedro_telemetry.plugin - INFO - Kedro is sending anonymous usage data with the sole purpose of improving the product. No personal data or IP addresses are stored on our side. If you want to opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment variables, or create a `.telemetry` file in the current working directory with the contents `consent: false`. Read more at https://docs.kedro.org/en/stable/configuration/telemetry.html
2025-05-28 22:17:34,945 - kedro.framework.project - INFO - Using 'conf/logging.yml' as logging configuration. You can change this by setting the KEDRO_LOGGING_CONFIG environment variable accordingly.
2025-05-28 22:17:35,017 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/kedro/io/data_catalog.py:165: KedroDeprecationWarning: `DataCatalog` has been deprecated and will be replaced by `KedroDataCatalog`, in Kedro 1.0.0.Currently some `KedroDataCatalog` APIs have been retained for compatibility with `DataCatalog`, including the `datasets` property and the `get_datasets`, `_get_datasets`, `add`,` list`, `add_feed_dict`, and `shallow_copy` methods. These will be removed or replaced with updated alternatives in Kedro 1.0.0. For more details, refer to the documentation: https://docs.kedro.org/en/stable/data/index.html#kedrodatacatalog-experimental-feature
  warnings.warn(

2025-05-28 22:17:37,937 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/mlflow/pyfunc/utils/data_validation.py:186: UserWarning: [33mAdd type hints to the `predict` method to enable data validation and automatic signature inference during model logging. Check https://mlflow.org/docs/latest/model/python_model.html#type-hint-usage-in-pythonmodel for more details.[0m
  color_warning(

2025-05-28 22:17:37,977 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/kedro/io/data_catalog.py:165: KedroDeprecationWarning: `DataCatalog` has been deprecated and will be replaced by `KedroDataCatalog`, in Kedro 1.0.0.Currently some `KedroDataCatalog` APIs have been retained for compatibility with `DataCatalog`, including the `datasets` property and the `get_datasets`, `_get_datasets`, `add`,` list`, `add_feed_dict`, and `shallow_copy` methods. These will be removed or replaced with updated alternatives in Kedro 1.0.0. For more details, refer to the documentation: https://docs.kedro.org/en/stable/data/index.html#kedrodatacatalog-experimental-feature
  warnings.warn(

2025-05-28 22:17:38,002 - kedro_telemetry.plugin - INFO - Kedro is sending anonymous usage data with the sole purpose of improving the product. No personal data or IP addresses are stored on our side. If you want to opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment variables, or create a `.telemetry` file in the current working directory with the contents `consent: false`. Read more at https://docs.kedro.org/en/stable/configuration/telemetry.html
2025-05-28 22:17:50,311 - kedro.framework.project - INFO - Using 'conf/logging.yml' as logging configuration. You can change this by setting the KEDRO_LOGGING_CONFIG environment variable accordingly.
2025-05-28 22:17:50,359 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/kedro/io/data_catalog.py:165: KedroDeprecationWarning: `DataCatalog` has been deprecated and will be replaced by `KedroDataCatalog`, in Kedro 1.0.0.Currently some `KedroDataCatalog` APIs have been retained for compatibility with `DataCatalog`, including the `datasets` property and the `get_datasets`, `_get_datasets`, `add`,` list`, `add_feed_dict`, and `shallow_copy` methods. These will be removed or replaced with updated alternatives in Kedro 1.0.0. For more details, refer to the documentation: https://docs.kedro.org/en/stable/data/index.html#kedrodatacatalog-experimental-feature
  warnings.warn(

2025-05-28 22:17:51,143 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/mlflow/pyfunc/utils/data_validation.py:186: UserWarning: [33mAdd type hints to the `predict` method to enable data validation and automatic signature inference during model logging. Check https://mlflow.org/docs/latest/model/python_model.html#type-hint-usage-in-pythonmodel for more details.[0m
  color_warning(

2025-05-28 22:17:51,183 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/kedro/io/data_catalog.py:165: KedroDeprecationWarning: `DataCatalog` has been deprecated and will be replaced by `KedroDataCatalog`, in Kedro 1.0.0.Currently some `KedroDataCatalog` APIs have been retained for compatibility with `DataCatalog`, including the `datasets` property and the `get_datasets`, `_get_datasets`, `add`,` list`, `add_feed_dict`, and `shallow_copy` methods. These will be removed or replaced with updated alternatives in Kedro 1.0.0. For more details, refer to the documentation: https://docs.kedro.org/en/stable/data/index.html#kedrodatacatalog-experimental-feature
  warnings.warn(

2025-05-28 22:17:51,225 - kedro.framework.session.session - INFO - Kedro project mlopsproject
2025-05-28 22:17:51,229 - kedro_mlflow.framework.hooks.mlflow_hook - INFO - Registering new custom resolver: 'km.random_name'
2025-05-28 22:17:51,234 - kedro_mlflow.config.kedro_mlflow_config - INFO - The 'tracking_uri' key in mlflow.yml is relative ('server.mlflow_(tracking|registry)_uri = mlruns'). It is converted to a valid uri: 'file:///Users/goncalopacheco/Documents/Master%27s/1%C2%BA%20Year/2%C2%BA%20semester/Machine%20Learning%20Operations/Project/mlopsproject/mlruns'
2025-05-28 22:17:53,715 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/kedro/io/core.py:355: KedroDeprecationWarning: The MatplotlibWriter class has been renamed to MatplotlibDataset. The MatplotlibWriter name is deprecated and will be removed in a future release.
  init_func(self, *args, **kwargs)

2025-05-28 22:17:53,717 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/kedro/io/data_catalog.py:165: KedroDeprecationWarning: `DataCatalog` has been deprecated and will be replaced by `KedroDataCatalog`, in Kedro 1.0.0.Currently some `KedroDataCatalog` APIs have been retained for compatibility with `DataCatalog`, including the `datasets` property and the `get_datasets`, `_get_datasets`, `add`,` list`, `add_feed_dict`, and `shallow_copy` methods. These will be removed or replaced with updated alternatives in Kedro 1.0.0. For more details, refer to the documentation: https://docs.kedro.org/en/stable/data/index.html#kedrodatacatalog-experimental-feature
  warnings.warn(

2025-05-28 22:17:53,722 - kedro_telemetry.plugin - INFO - Kedro is sending anonymous usage data with the sole purpose of improving the product. No personal data or IP addresses are stored on our side. If you want to opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment variables, or create a `.telemetry` file in the current working directory with the contents `consent: false`. Read more at https://docs.kedro.org/en/stable/configuration/telemetry.html
2025-05-28 22:17:54,290 - kedro_mlflow.framework.hooks.mlflow_hook - INFO - Mlflow run '__default__' - '1290d492484a4860b62939e94e7d278f' has started
2025-05-28 22:17:54,292 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/kedro/io/data_catalog.py:165: KedroDeprecationWarning: `DataCatalog` has been deprecated and will be replaced by `KedroDataCatalog`, in Kedro 1.0.0.Currently some `KedroDataCatalog` APIs have been retained for compatibility with `DataCatalog`, including the `datasets` property and the `get_datasets`, `_get_datasets`, `add`,` list`, `add_feed_dict`, and `shallow_copy` methods. These will be removed or replaced with updated alternatives in Kedro 1.0.0. For more details, refer to the documentation: https://docs.kedro.org/en/stable/data/index.html#kedrodatacatalog-experimental-feature
  warnings.warn(

2025-05-28 22:17:54,293 - kedro.runner.sequential_runner - INFO - Using synchronous mode for loading and saving data. Use the --async flag for potential performance gains. https://docs.kedro.org/en/stable/nodes_and_pipelines/run_a_pipeline.html#load-and-save-asynchronously
2025-05-28 22:17:54,294 - kedro.io.data_catalog - INFO - Loading data from companies (CSVDataset)...
2025-05-28 22:17:54,308 - kedro_mlflow.framework.hooks.mlflow_hook - INFO - Restarting mlflow run '__default__' - '1290d492484a4860b62939e94e7d278f' at node level for multi-threading
2025-05-28 22:17:54,308 - kedro.pipeline.node - INFO - Running node: create_confusion_matrix([companies]) -> [dummy_confusion_matrix]
2025-05-28 22:17:54,497 - kedro.io.data_catalog - INFO - Saving data to dummy_confusion_matrix (MatplotlibWriter)...
2025-05-28 22:17:54,532 - kedro.runner.sequential_runner - INFO - Completed node: create_confusion_matrix([companies]) -> [dummy_confusion_matrix]
2025-05-28 22:17:54,532 - kedro.runner.sequential_runner - INFO - Completed 1 out of 9 tasks
2025-05-28 22:17:54,533 - kedro.io.data_catalog - INFO - Loading data from companies (CSVDataset)...
2025-05-28 22:17:54,540 - kedro_mlflow.framework.hooks.mlflow_hook - INFO - Restarting mlflow run '__default__' - '1290d492484a4860b62939e94e7d278f' at node level for multi-threading
2025-05-28 22:17:54,541 - kedro.pipeline.node - INFO - Running node: preprocess_companies_node: preprocess_companies([companies]) -> [preprocessed_companies]
2025-05-28 22:17:54,548 - kedro.io.data_catalog - INFO - Saving data to preprocessed_companies (ParquetDataset)...
2025-05-28 22:17:54,601 - kedro.runner.sequential_runner - INFO - Completed node: preprocess_companies_node
2025-05-28 22:17:54,602 - kedro.runner.sequential_runner - INFO - Completed 2 out of 9 tasks
2025-05-28 22:17:54,602 - kedro.io.data_catalog - INFO - Loading data from shuttles (ExcelDataset)...
2025-05-28 22:17:55,589 - kedro_mlflow.framework.hooks.mlflow_hook - INFO - Restarting mlflow run '__default__' - '1290d492484a4860b62939e94e7d278f' at node level for multi-threading
2025-05-28 22:17:55,590 - kedro.pipeline.node - INFO - Running node: preprocess_shuttles_node: preprocess_shuttles([shuttles]) -> [preprocessed_shuttles]
2025-05-28 22:17:55,607 - kedro.io.data_catalog - INFO - Saving data to preprocessed_shuttles (ParquetDataset)...
2025-05-28 22:17:55,619 - kedro.runner.sequential_runner - INFO - Completed node: preprocess_shuttles_node
2025-05-28 22:17:55,619 - kedro.runner.sequential_runner - INFO - Completed 3 out of 9 tasks
2025-05-28 22:17:55,619 - kedro.io.data_catalog - INFO - Loading data from preprocessed_shuttles (ParquetDataset)...
2025-05-28 22:17:55,802 - kedro_mlflow.framework.hooks.mlflow_hook - INFO - Restarting mlflow run '__default__' - '1290d492484a4860b62939e94e7d278f' at node level for multi-threading
2025-05-28 22:17:55,803 - kedro.pipeline.node - INFO - Running node: compare_passenger_capacity_exp([preprocessed_shuttles]) -> [shuttle_passenger_capacity_plot_exp]
2025-05-28 22:17:55,816 - kedro.io.data_catalog - INFO - Saving data to shuttle_passenger_capacity_plot_exp (PlotlyDataset)...
2025-05-28 22:17:56,117 - kedro.runner.sequential_runner - INFO - Completed node: compare_passenger_capacity_exp([preprocessed_shuttles]) -> [shuttle_passenger_capacity_plot_exp]
2025-05-28 22:17:56,118 - kedro.runner.sequential_runner - INFO - Completed 4 out of 9 tasks
2025-05-28 22:17:56,118 - kedro.io.data_catalog - INFO - Loading data from preprocessed_shuttles (ParquetDataset)...
2025-05-28 22:17:56,129 - kedro_mlflow.framework.hooks.mlflow_hook - INFO - Restarting mlflow run '__default__' - '1290d492484a4860b62939e94e7d278f' at node level for multi-threading
2025-05-28 22:17:56,130 - kedro.pipeline.node - INFO - Running node: compare_passenger_capacity_go([preprocessed_shuttles]) -> [shuttle_passenger_capacity_plot_go]
2025-05-28 22:17:56,137 - kedro.io.data_catalog - INFO - Saving data to shuttle_passenger_capacity_plot_go (JSONDataset)...
2025-05-28 22:17:56,139 - kedro.runner.sequential_runner - INFO - Completed node: compare_passenger_capacity_go([preprocessed_shuttles]) -> [shuttle_passenger_capacity_plot_go]
2025-05-28 22:17:56,140 - kedro.runner.sequential_runner - INFO - Completed 5 out of 9 tasks
2025-05-28 22:17:56,140 - kedro.io.data_catalog - INFO - Loading data from preprocessed_shuttles (ParquetDataset)...
2025-05-28 22:17:56,146 - kedro.io.data_catalog - INFO - Loading data from preprocessed_companies (ParquetDataset)...
2025-05-28 22:17:56,149 - kedro.io.data_catalog - INFO - Loading data from reviews (CSVDataset)...
2025-05-28 22:17:56,168 - kedro_mlflow.framework.hooks.mlflow_hook - INFO - Restarting mlflow run '__default__' - '1290d492484a4860b62939e94e7d278f' at node level for multi-threading
2025-05-28 22:17:56,168 - kedro.pipeline.node - INFO - Running node: create_model_input_table_node: create_model_input_table([preprocessed_shuttles;preprocessed_companies;reviews]) -> [model_input_table]
2025-05-28 22:17:56,194 - kedro.io.data_catalog - INFO - Saving data to model_input_table (ParquetDataset)...
2025-05-28 22:17:56,207 - kedro.runner.sequential_runner - INFO - Completed node: create_model_input_table_node
2025-05-28 22:17:56,207 - kedro.runner.sequential_runner - INFO - Completed 6 out of 9 tasks
2025-05-28 22:17:56,208 - kedro.io.data_catalog - INFO - Loading data from model_input_table (ParquetDataset)...
2025-05-28 22:17:56,216 - kedro.io.data_catalog - INFO - Loading data from params:model_options (MemoryDataset)...
2025-05-28 22:17:56,225 - kedro_mlflow.framework.hooks.mlflow_hook - INFO - Restarting mlflow run '__default__' - '1290d492484a4860b62939e94e7d278f' at node level for multi-threading
2025-05-28 22:17:56,226 - kedro.pipeline.node - INFO - Running node: split_data_node: split_data([model_input_table;params:model_options]) -> [X_train;X_test;y_train;y_test]
2025-05-28 22:17:56,242 - kedro.io.data_catalog - INFO - Saving data to X_train (MemoryDataset)...
2025-05-28 22:17:56,247 - kedro.io.data_catalog - INFO - Saving data to X_test (MemoryDataset)...
2025-05-28 22:17:56,250 - kedro.io.data_catalog - INFO - Saving data to y_train (MemoryDataset)...
2025-05-28 22:17:56,251 - kedro.io.data_catalog - INFO - Saving data to y_test (MemoryDataset)...
2025-05-28 22:17:56,252 - kedro.runner.sequential_runner - INFO - Completed node: split_data_node
2025-05-28 22:17:56,253 - kedro.runner.sequential_runner - INFO - Completed 7 out of 9 tasks
2025-05-28 22:17:56,253 - kedro.io.data_catalog - INFO - Loading data from X_train (MemoryDataset)...
2025-05-28 22:17:56,256 - kedro.io.data_catalog - INFO - Loading data from y_train (MemoryDataset)...
2025-05-28 22:17:56,261 - kedro_mlflow.framework.hooks.mlflow_hook - INFO - Restarting mlflow run '__default__' - '1290d492484a4860b62939e94e7d278f' at node level for multi-threading
2025-05-28 22:17:56,262 - kedro.pipeline.node - INFO - Running node: train_model_node: train_model([X_train;y_train]) -> [regressor]
2025-05-28 22:17:56,267 - kedro.io.data_catalog - INFO - Saving data to regressor (PickleDataset)...
2025-05-28 22:17:56,269 - kedro.runner.sequential_runner - INFO - Completed node: train_model_node
2025-05-28 22:17:56,269 - kedro.runner.sequential_runner - INFO - Completed 8 out of 9 tasks
2025-05-28 22:17:56,270 - kedro.io.data_catalog - INFO - Loading data from regressor (PickleDataset)...
2025-05-28 22:17:56,270 - kedro.io.data_catalog - INFO - Loading data from X_test (MemoryDataset)...
2025-05-28 22:17:56,273 - kedro.io.data_catalog - INFO - Loading data from y_test (MemoryDataset)...
2025-05-28 22:17:56,279 - kedro_mlflow.framework.hooks.mlflow_hook - INFO - Restarting mlflow run '__default__' - '1290d492484a4860b62939e94e7d278f' at node level for multi-threading
2025-05-28 22:17:56,279 - kedro.pipeline.node - INFO - Running node: evaluate_model_node: evaluate_model([regressor;X_test;y_test]) -> None
2025-05-28 22:17:56,281 - mlopsproject.pipelines.data_science.nodes - INFO - Model has a coefficient R^2 of 0.387 on test data.
2025-05-28 22:17:56,285 - kedro.runner.sequential_runner - INFO - Completed node: evaluate_model_node
2025-05-28 22:17:56,285 - kedro.runner.sequential_runner - INFO - Completed 9 out of 9 tasks
2025-05-28 22:17:56,285 - kedro.runner.sequential_runner - INFO - Pipeline execution completed successfully.
2025-05-29 14:09:44,413 - kedro.framework.project - INFO - Using 'conf/logging.yml' as logging configuration. You can change this by setting the KEDRO_LOGGING_CONFIG environment variable accordingly.
2025-05-29 14:09:44,582 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/kedro/io/data_catalog.py:165: KedroDeprecationWarning: `DataCatalog` has been deprecated and will be replaced by `KedroDataCatalog`, in Kedro 1.0.0.Currently some `KedroDataCatalog` APIs have been retained for compatibility with `DataCatalog`, including the `datasets` property and the `get_datasets`, `_get_datasets`, `add`,` list`, `add_feed_dict`, and `shallow_copy` methods. These will be removed or replaced with updated alternatives in Kedro 1.0.0. For more details, refer to the documentation: https://docs.kedro.org/en/stable/data/index.html#kedrodatacatalog-experimental-feature
  warnings.warn(

2025-05-29 14:09:47,775 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/mlflow/pyfunc/utils/data_validation.py:186: UserWarning: [33mAdd type hints to the `predict` method to enable data validation and automatic signature inference during model logging. Check https://mlflow.org/docs/latest/model/python_model.html#type-hint-usage-in-pythonmodel for more details.[0m
  color_warning(

2025-05-29 14:09:47,814 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/kedro/io/data_catalog.py:165: KedroDeprecationWarning: `DataCatalog` has been deprecated and will be replaced by `KedroDataCatalog`, in Kedro 1.0.0.Currently some `KedroDataCatalog` APIs have been retained for compatibility with `DataCatalog`, including the `datasets` property and the `get_datasets`, `_get_datasets`, `add`,` list`, `add_feed_dict`, and `shallow_copy` methods. These will be removed or replaced with updated alternatives in Kedro 1.0.0. For more details, refer to the documentation: https://docs.kedro.org/en/stable/data/index.html#kedrodatacatalog-experimental-feature
  warnings.warn(

2025-05-29 14:09:47,862 - kedro.framework.session.session - INFO - Kedro project mlopsproject
2025-05-29 14:09:47,867 - kedro_mlflow.framework.hooks.mlflow_hook - INFO - Registering new custom resolver: 'km.random_name'
2025-05-29 14:09:47,872 - kedro_mlflow.config.kedro_mlflow_config - INFO - The 'tracking_uri' key in mlflow.yml is relative ('server.mlflow_(tracking|registry)_uri = mlruns'). It is converted to a valid uri: 'file:///Users/goncalopacheco/Documents/Master%27s/1%C2%BA%20Year/2%C2%BA%20semester/Machine%20Learning%20Operations/Project/mlopsproject/mlruns'
2025-05-29 14:09:50,300 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/kedro/io/data_catalog.py:165: KedroDeprecationWarning: `DataCatalog` has been deprecated and will be replaced by `KedroDataCatalog`, in Kedro 1.0.0.Currently some `KedroDataCatalog` APIs have been retained for compatibility with `DataCatalog`, including the `datasets` property and the `get_datasets`, `_get_datasets`, `add`,` list`, `add_feed_dict`, and `shallow_copy` methods. These will be removed or replaced with updated alternatives in Kedro 1.0.0. For more details, refer to the documentation: https://docs.kedro.org/en/stable/data/index.html#kedrodatacatalog-experimental-feature
  warnings.warn(

2025-05-29 14:09:50,306 - kedro_telemetry.plugin - INFO - Kedro is sending anonymous usage data with the sole purpose of improving the product. No personal data or IP addresses are stored on our side. If you want to opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment variables, or create a `.telemetry` file in the current working directory with the contents `consent: false`. Read more at https://docs.kedro.org/en/stable/configuration/telemetry.html
2025-05-29 14:09:50,905 - kedro_mlflow.framework.hooks.mlflow_hook - INFO - Mlflow run '__default__' - 'e6ec6527e5974eabb1985bf43b40b786' has started
2025-05-29 14:09:50,907 - kedro_mlflow.framework.hooks.mlflow_hook - INFO - The run 'e6ec6527e5974eabb1985bf43b40b786' was closed because of an error in the pipeline.
2025-06-24 20:53:32,462 - kedro.framework.project - INFO - Using 'conf/logging.yml' as logging configuration. You can change this by setting the KEDRO_LOGGING_CONFIG environment variable accordingly.
2025-06-24 20:53:32,659 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/cli/utils.py:111: KedroDeprecationWarning: DeprecationWarning: 'kedro run' flag '--namespace' is deprecated and will be replaced with '--namespaces' from Kedro 1.0.0 to allow running multiple namespaces. 
  warnings.warn(message, KedroDeprecationWarning)

2025-06-24 20:53:32,706 - kedro.framework.session.session - INFO - Kedro project MLopsProject
2025-06-24 20:53:32,714 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py:349: UserWarning: The 'mlopsproject.pipelines.ingestion' module does not expose a 'create_pipeline' function, so no pipelines defined therein will be returned by 'find_pipelines'.
  warnings.warn(

2025-06-24 20:53:32,715 - kedro_telemetry.plugin - INFO - Kedro is sending anonymous usage data with the sole purpose of improving the product. No personal data or IP addresses are stored on our side. If you want to opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment variables, or create a `.telemetry` file in the current working directory with the contents `consent: false`. Read more at https://docs.kedro.org/en/stable/configuration/telemetry.html
2025-06-24 20:55:17,340 - kedro.framework.project - INFO - Using 'conf/logging.yml' as logging configuration. You can change this by setting the KEDRO_LOGGING_CONFIG environment variable accordingly.
2025-06-24 20:55:17,518 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/cli/utils.py:111: KedroDeprecationWarning: DeprecationWarning: 'kedro run' flag '--namespace' is deprecated and will be replaced with '--namespaces' from Kedro 1.0.0 to allow running multiple namespaces. 
  warnings.warn(message, KedroDeprecationWarning)

2025-06-24 20:55:17,541 - kedro.framework.session.session - INFO - Kedro project MLopsProject
2025-06-24 20:55:17,549 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py:349: UserWarning: The 'mlopsproject.pipelines.ingestion' module does not expose a 'create_pipeline' function, so no pipelines defined therein will be returned by 'find_pipelines'.
  warnings.warn(

2025-06-24 20:55:17,550 - kedro_telemetry.plugin - INFO - Kedro is sending anonymous usage data with the sole purpose of improving the product. No personal data or IP addresses are stored on our side. If you want to opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment variables, or create a `.telemetry` file in the current working directory with the contents `consent: false`. Read more at https://docs.kedro.org/en/stable/configuration/telemetry.html
2025-06-24 21:17:18,220 - kedro.framework.project - INFO - Using 'conf/logging.yml' as logging configuration. You can change this by setting the KEDRO_LOGGING_CONFIG environment variable accordingly.
2025-06-24 21:17:18,397 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/cli/utils.py:111: KedroDeprecationWarning: DeprecationWarning: 'kedro run' flag '--namespace' is deprecated and will be replaced with '--namespaces' from Kedro 1.0.0 to allow running multiple namespaces. 
  warnings.warn(message, KedroDeprecationWarning)

2025-06-24 21:17:18,423 - kedro.framework.session.session - INFO - Kedro project MLopsProject
2025-06-24 21:17:18,431 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py:349: UserWarning: The 'mlopsproject.pipelines.ingestion' module does not expose a 'create_pipeline' function, so no pipelines defined therein will be returned by 'find_pipelines'.
  warnings.warn(

2025-06-24 21:17:18,432 - kedro_telemetry.plugin - INFO - Kedro is sending anonymous usage data with the sole purpose of improving the product. No personal data or IP addresses are stored on our side. If you want to opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment variables, or create a `.telemetry` file in the current working directory with the contents `consent: false`. Read more at https://docs.kedro.org/en/stable/configuration/telemetry.html
2025-06-24 21:18:19,656 - kedro.framework.project - INFO - Using 'conf/logging.yml' as logging configuration. You can change this by setting the KEDRO_LOGGING_CONFIG environment variable accordingly.
2025-06-24 21:20:44,159 - kedro.framework.project - INFO - Using 'conf/logging.yml' as logging configuration. You can change this by setting the KEDRO_LOGGING_CONFIG environment variable accordingly.
2025-06-24 21:21:27,877 - kedro.framework.project - INFO - Using 'conf/logging.yml' as logging configuration. You can change this by setting the KEDRO_LOGGING_CONFIG environment variable accordingly.
2025-06-24 21:21:28,040 - kedro_telemetry.plugin - INFO - Kedro is sending anonymous usage data with the sole purpose of improving the product. No personal data or IP addresses are stored on our side. If you want to opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment variables, or create a `.telemetry` file in the current working directory with the contents `consent: false`. Read more at https://docs.kedro.org/en/stable/configuration/telemetry.html
2025-06-24 21:21:45,608 - kedro.framework.project - INFO - Using 'conf/logging.yml' as logging configuration. You can change this by setting the KEDRO_LOGGING_CONFIG environment variable accordingly.
2025-06-24 21:21:45,733 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/cli/utils.py:111: KedroDeprecationWarning: DeprecationWarning: 'kedro run' flag '--namespace' is deprecated and will be replaced with '--namespaces' from Kedro 1.0.0 to allow running multiple namespaces. 
  warnings.warn(message, KedroDeprecationWarning)

2025-06-24 21:21:45,758 - kedro.framework.session.session - INFO - Kedro project MLopsProject
2025-06-24 21:21:45,765 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py:349: UserWarning: The 'mlopsproject.pipelines.ingestion' module does not expose a 'create_pipeline' function, so no pipelines defined therein will be returned by 'find_pipelines'.
  warnings.warn(

2025-06-24 21:21:45,767 - kedro_telemetry.plugin - INFO - Kedro is sending anonymous usage data with the sole purpose of improving the product. No personal data or IP addresses are stored on our side. If you want to opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment variables, or create a `.telemetry` file in the current working directory with the contents `consent: false`. Read more at https://docs.kedro.org/en/stable/configuration/telemetry.html
2025-06-24 21:25:09,304 - kedro.framework.project - INFO - Using 'conf/logging.yml' as logging configuration. You can change this by setting the KEDRO_LOGGING_CONFIG environment variable accordingly.
2025-06-24 21:25:09,480 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/cli/utils.py:111: KedroDeprecationWarning: DeprecationWarning: 'kedro run' flag '--namespace' is deprecated and will be replaced with '--namespaces' from Kedro 1.0.0 to allow running multiple namespaces. 
  warnings.warn(message, KedroDeprecationWarning)

2025-06-24 21:25:09,512 - kedro.framework.session.session - INFO - Kedro project MLopsProject
2025-06-24 21:25:09,519 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py:349: UserWarning: The 'mlopsproject.pipelines.ingestion' module does not expose a 'create_pipeline' function, so no pipelines defined therein will be returned by 'find_pipelines'.
  warnings.warn(

2025-06-24 21:25:09,521 - kedro_telemetry.plugin - INFO - Kedro is sending anonymous usage data with the sole purpose of improving the product. No personal data or IP addresses are stored on our side. If you want to opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment variables, or create a `.telemetry` file in the current working directory with the contents `consent: false`. Read more at https://docs.kedro.org/en/stable/configuration/telemetry.html
2025-06-24 21:37:43,343 - kedro.framework.project - INFO - Using 'conf/logging.yml' as logging configuration. You can change this by setting the KEDRO_LOGGING_CONFIG environment variable accordingly.
2025-06-24 21:37:43,518 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/cli/utils.py:111: KedroDeprecationWarning: DeprecationWarning: 'kedro run' flag '--namespace' is deprecated and will be replaced with '--namespaces' from Kedro 1.0.0 to allow running multiple namespaces. 
  warnings.warn(message, KedroDeprecationWarning)

2025-06-24 21:37:43,540 - kedro.framework.session.session - INFO - Kedro project MLopsProject
2025-06-24 21:37:44,017 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py:452: UserWarning: An error occurred while importing the 'mlopsproject.pipelines.ingestion' module. Nothing defined therein will be returned by 'find_pipelines'.

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py", line 444, in find_pipelines
    pipeline_module = importlib.import_module(pipeline_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/ingestion/__init__.py", line 1, in <module>
    from .pipeline import create_pipeline
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/ingestion/pipeline.py", line 4, in <module>
    from .nodes import ingestion_heart
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/ingestion/nodes.py", line 10, in <module>
    from great_expectations.core import ExpectationSuite, ExpectationConfiguration
ModuleNotFoundError: No module named 'great_expectations'

  warnings.warn(

2025-06-24 21:37:44,023 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py:452: UserWarning: An error occurred while importing the 'mlopsproject.pipelines.data_unit_tests' module. Nothing defined therein will be returned by 'find_pipelines'.

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py", line 444, in find_pipelines
    pipeline_module = importlib.import_module(pipeline_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/data_unit_tests/__init__.py", line 1, in <module>
    from .pipeline import create_pipeline
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/data_unit_tests/pipeline.py", line 4, in <module>
    from .nodes import test_heart_data
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/data_unit_tests/nodes.py", line 4, in <module>
    from great_expectations.core import ExpectationSuite, ExpectationConfiguration
ModuleNotFoundError: No module named 'great_expectations'

  warnings.warn(

2025-06-24 21:37:44,662 - kedro_telemetry.plugin - INFO - Kedro is sending anonymous usage data with the sole purpose of improving the product. No personal data or IP addresses are stored on our side. If you want to opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment variables, or create a `.telemetry` file in the current working directory with the contents `consent: false`. Read more at https://docs.kedro.org/en/stable/configuration/telemetry.html
2025-06-24 21:38:22,443 - kedro.framework.project - INFO - Using 'conf/logging.yml' as logging configuration. You can change this by setting the KEDRO_LOGGING_CONFIG environment variable accordingly.
2025-06-24 21:38:22,607 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/cli/utils.py:111: KedroDeprecationWarning: DeprecationWarning: 'kedro run' flag '--namespace' is deprecated and will be replaced with '--namespaces' from Kedro 1.0.0 to allow running multiple namespaces. 
  warnings.warn(message, KedroDeprecationWarning)

2025-06-24 21:38:22,643 - kedro.framework.session.session - INFO - Kedro project MLopsProject
2025-06-24 21:38:23,154 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py:452: UserWarning: An error occurred while importing the 'mlopsproject.pipelines.ingestion' module. Nothing defined therein will be returned by 'find_pipelines'.

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py", line 444, in find_pipelines
    pipeline_module = importlib.import_module(pipeline_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/ingestion/__init__.py", line 1, in <module>
    from .pipeline import create_pipeline
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/ingestion/pipeline.py", line 4, in <module>
    from .nodes import ingestion_heart
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/ingestion/nodes.py", line 10, in <module>
    from great_expectations.core import ExpectationSuite, ExpectationConfiguration
ModuleNotFoundError: No module named 'great_expectations'

  warnings.warn(

2025-06-24 21:38:23,158 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py:452: UserWarning: An error occurred while importing the 'mlopsproject.pipelines.data_unit_tests' module. Nothing defined therein will be returned by 'find_pipelines'.

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py", line 444, in find_pipelines
    pipeline_module = importlib.import_module(pipeline_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/data_unit_tests/__init__.py", line 1, in <module>
    from .pipeline import create_pipeline
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/data_unit_tests/pipeline.py", line 4, in <module>
    from .nodes import test_heart_data
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/data_unit_tests/nodes.py", line 4, in <module>
    from great_expectations.core import ExpectationSuite, ExpectationConfiguration
ModuleNotFoundError: No module named 'great_expectations'

  warnings.warn(

2025-06-24 21:38:23,769 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/io/core.py:575: UserWarning: Since kedro-datasets 2.0, 'Dataset' is spelled with a lowercase 's'. Got 'pandas.ParquetDataSet'.
  warnings.warn(

2025-06-24 21:38:23,771 - kedro_telemetry.plugin - INFO - Kedro is sending anonymous usage data with the sole purpose of improving the product. No personal data or IP addresses are stored on our side. If you want to opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment variables, or create a `.telemetry` file in the current working directory with the contents `consent: false`. Read more at https://docs.kedro.org/en/stable/configuration/telemetry.html
2025-06-24 21:39:01,944 - kedro.framework.project - INFO - Using 'conf/logging.yml' as logging configuration. You can change this by setting the KEDRO_LOGGING_CONFIG environment variable accordingly.
2025-06-24 21:39:02,107 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/cli/utils.py:111: KedroDeprecationWarning: DeprecationWarning: 'kedro run' flag '--namespace' is deprecated and will be replaced with '--namespaces' from Kedro 1.0.0 to allow running multiple namespaces. 
  warnings.warn(message, KedroDeprecationWarning)

2025-06-24 21:39:02,139 - kedro.framework.session.session - INFO - Kedro project MLopsProject
2025-06-24 21:39:02,636 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py:452: UserWarning: An error occurred while importing the 'mlopsproject.pipelines.ingestion' module. Nothing defined therein will be returned by 'find_pipelines'.

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py", line 444, in find_pipelines
    pipeline_module = importlib.import_module(pipeline_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/ingestion/__init__.py", line 1, in <module>
    from .pipeline import create_pipeline
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/ingestion/pipeline.py", line 4, in <module>
    from .nodes import ingestion_heart
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/ingestion/nodes.py", line 10, in <module>
    from great_expectations.core import ExpectationSuite, ExpectationConfiguration
ModuleNotFoundError: No module named 'great_expectations'

  warnings.warn(

2025-06-24 21:39:02,641 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py:452: UserWarning: An error occurred while importing the 'mlopsproject.pipelines.data_unit_tests' module. Nothing defined therein will be returned by 'find_pipelines'.

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py", line 444, in find_pipelines
    pipeline_module = importlib.import_module(pipeline_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/data_unit_tests/__init__.py", line 1, in <module>
    from .pipeline import create_pipeline
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/data_unit_tests/pipeline.py", line 4, in <module>
    from .nodes import test_heart_data
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/data_unit_tests/nodes.py", line 4, in <module>
    from great_expectations.core import ExpectationSuite, ExpectationConfiguration
ModuleNotFoundError: No module named 'great_expectations'

  warnings.warn(

2025-06-24 21:39:03,239 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/io/core.py:575: UserWarning: Since kedro-datasets 2.0, 'Dataset' is spelled with a lowercase 's'. Got 'pandas.ParquetDataSet'.
  warnings.warn(

2025-06-24 21:39:03,241 - kedro_telemetry.plugin - INFO - Kedro is sending anonymous usage data with the sole purpose of improving the product. No personal data or IP addresses are stored on our side. If you want to opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment variables, or create a `.telemetry` file in the current working directory with the contents `consent: false`. Read more at https://docs.kedro.org/en/stable/configuration/telemetry.html
2025-06-24 21:39:20,450 - kedro.framework.project - INFO - Using 'conf/logging.yml' as logging configuration. You can change this by setting the KEDRO_LOGGING_CONFIG environment variable accordingly.
2025-06-24 21:39:20,588 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/cli/utils.py:111: KedroDeprecationWarning: DeprecationWarning: 'kedro run' flag '--namespace' is deprecated and will be replaced with '--namespaces' from Kedro 1.0.0 to allow running multiple namespaces. 
  warnings.warn(message, KedroDeprecationWarning)

2025-06-24 21:39:20,610 - kedro.framework.session.session - INFO - Kedro project MLopsProject
2025-06-24 21:39:20,950 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py:452: UserWarning: An error occurred while importing the 'mlopsproject.pipelines.ingestion' module. Nothing defined therein will be returned by 'find_pipelines'.

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py", line 444, in find_pipelines
    pipeline_module = importlib.import_module(pipeline_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/ingestion/__init__.py", line 1, in <module>
    from .pipeline import create_pipeline
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/ingestion/pipeline.py", line 4, in <module>
    from .nodes import ingestion_heart
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/ingestion/nodes.py", line 10, in <module>
    from great_expectations.core import ExpectationSuite, ExpectationConfiguration
ModuleNotFoundError: No module named 'great_expectations'

  warnings.warn(

2025-06-24 21:39:20,955 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py:452: UserWarning: An error occurred while importing the 'mlopsproject.pipelines.data_unit_tests' module. Nothing defined therein will be returned by 'find_pipelines'.

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py", line 444, in find_pipelines
    pipeline_module = importlib.import_module(pipeline_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/data_unit_tests/__init__.py", line 1, in <module>
    from .pipeline import create_pipeline
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/data_unit_tests/pipeline.py", line 4, in <module>
    from .nodes import test_heart_data
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/data_unit_tests/nodes.py", line 4, in <module>
    from great_expectations.core import ExpectationSuite, ExpectationConfiguration
ModuleNotFoundError: No module named 'great_expectations'

  warnings.warn(

2025-06-24 21:39:21,526 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/io/core.py:575: UserWarning: Since kedro-datasets 2.0, 'Dataset' is spelled with a lowercase 's'. Got 'pandas.ParquetDataSet'.
  warnings.warn(

2025-06-24 21:39:21,528 - kedro_telemetry.plugin - INFO - Kedro is sending anonymous usage data with the sole purpose of improving the product. No personal data or IP addresses are stored on our side. If you want to opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment variables, or create a `.telemetry` file in the current working directory with the contents `consent: false`. Read more at https://docs.kedro.org/en/stable/configuration/telemetry.html
2025-06-24 21:39:48,229 - kedro.framework.project - INFO - Using 'conf/logging.yml' as logging configuration. You can change this by setting the KEDRO_LOGGING_CONFIG environment variable accordingly.
2025-06-24 21:39:48,390 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/cli/utils.py:111: KedroDeprecationWarning: DeprecationWarning: 'kedro run' flag '--namespace' is deprecated and will be replaced with '--namespaces' from Kedro 1.0.0 to allow running multiple namespaces. 
  warnings.warn(message, KedroDeprecationWarning)

2025-06-24 21:39:48,420 - kedro.framework.session.session - INFO - Kedro project MLopsProject
2025-06-24 21:39:48,895 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py:452: UserWarning: An error occurred while importing the 'mlopsproject.pipelines.ingestion' module. Nothing defined therein will be returned by 'find_pipelines'.

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py", line 444, in find_pipelines
    pipeline_module = importlib.import_module(pipeline_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/ingestion/__init__.py", line 1, in <module>
    from .pipeline import create_pipeline
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/ingestion/pipeline.py", line 4, in <module>
    from .nodes import ingestion_heart
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/ingestion/nodes.py", line 10, in <module>
    from great_expectations.core import ExpectationSuite, ExpectationConfiguration
ModuleNotFoundError: No module named 'great_expectations'

  warnings.warn(

2025-06-24 21:39:48,900 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py:452: UserWarning: An error occurred while importing the 'mlopsproject.pipelines.data_unit_tests' module. Nothing defined therein will be returned by 'find_pipelines'.

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py", line 444, in find_pipelines
    pipeline_module = importlib.import_module(pipeline_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/data_unit_tests/__init__.py", line 1, in <module>
    from .pipeline import create_pipeline
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/data_unit_tests/pipeline.py", line 4, in <module>
    from .nodes import test_heart_data
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/data_unit_tests/nodes.py", line 4, in <module>
    from great_expectations.core import ExpectationSuite, ExpectationConfiguration
ModuleNotFoundError: No module named 'great_expectations'

  warnings.warn(

2025-06-24 21:39:49,506 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/io/core.py:575: UserWarning: Since kedro-datasets 2.0, 'Dataset' is spelled with a lowercase 's'. Got 'pandas.ParquetDataSet'.
  warnings.warn(

2025-06-24 21:39:49,508 - kedro_telemetry.plugin - INFO - Kedro is sending anonymous usage data with the sole purpose of improving the product. No personal data or IP addresses are stored on our side. If you want to opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment variables, or create a `.telemetry` file in the current working directory with the contents `consent: false`. Read more at https://docs.kedro.org/en/stable/configuration/telemetry.html
2025-06-24 21:40:30,391 - kedro.framework.project - INFO - Using 'conf/logging.yml' as logging configuration. You can change this by setting the KEDRO_LOGGING_CONFIG environment variable accordingly.
2025-06-24 21:40:30,562 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/cli/utils.py:111: KedroDeprecationWarning: DeprecationWarning: 'kedro run' flag '--namespace' is deprecated and will be replaced with '--namespaces' from Kedro 1.0.0 to allow running multiple namespaces. 
  warnings.warn(message, KedroDeprecationWarning)

2025-06-24 21:40:30,586 - kedro.framework.session.session - INFO - Kedro project MLopsProject
2025-06-24 21:40:31,082 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py:452: UserWarning: An error occurred while importing the 'mlopsproject.pipelines.ingestion' module. Nothing defined therein will be returned by 'find_pipelines'.

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py", line 444, in find_pipelines
    pipeline_module = importlib.import_module(pipeline_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/ingestion/__init__.py", line 1, in <module>
    from .pipeline import create_pipeline
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/ingestion/pipeline.py", line 4, in <module>
    from .nodes import ingestion_heart
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/ingestion/nodes.py", line 10, in <module>
    from great_expectations.core import ExpectationSuite, ExpectationConfiguration
ModuleNotFoundError: No module named 'great_expectations'

  warnings.warn(

2025-06-24 21:40:31,087 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py:452: UserWarning: An error occurred while importing the 'mlopsproject.pipelines.data_unit_tests' module. Nothing defined therein will be returned by 'find_pipelines'.

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py", line 444, in find_pipelines
    pipeline_module = importlib.import_module(pipeline_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/data_unit_tests/__init__.py", line 1, in <module>
    from .pipeline import create_pipeline
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/data_unit_tests/pipeline.py", line 4, in <module>
    from .nodes import test_heart_data
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/data_unit_tests/nodes.py", line 4, in <module>
    from great_expectations.core import ExpectationSuite, ExpectationConfiguration
ModuleNotFoundError: No module named 'great_expectations'

  warnings.warn(

2025-06-24 21:40:31,680 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/io/core.py:575: UserWarning: Since kedro-datasets 2.0, 'Dataset' is spelled with a lowercase 's'. Got 'pandas.CSVDataSet'.
  warnings.warn(

2025-06-24 21:40:31,682 - kedro_telemetry.plugin - INFO - Kedro is sending anonymous usage data with the sole purpose of improving the product. No personal data or IP addresses are stored on our side. If you want to opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment variables, or create a `.telemetry` file in the current working directory with the contents `consent: false`. Read more at https://docs.kedro.org/en/stable/configuration/telemetry.html
2025-06-24 21:41:05,466 - kedro.framework.project - INFO - Using 'conf/logging.yml' as logging configuration. You can change this by setting the KEDRO_LOGGING_CONFIG environment variable accordingly.
2025-06-24 21:41:05,635 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/cli/utils.py:111: KedroDeprecationWarning: DeprecationWarning: 'kedro run' flag '--namespace' is deprecated and will be replaced with '--namespaces' from Kedro 1.0.0 to allow running multiple namespaces. 
  warnings.warn(message, KedroDeprecationWarning)

2025-06-24 21:41:05,668 - kedro.framework.session.session - INFO - Kedro project MLopsProject
2025-06-24 21:41:06,147 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py:452: UserWarning: An error occurred while importing the 'mlopsproject.pipelines.ingestion' module. Nothing defined therein will be returned by 'find_pipelines'.

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py", line 444, in find_pipelines
    pipeline_module = importlib.import_module(pipeline_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/ingestion/__init__.py", line 1, in <module>
    from .pipeline import create_pipeline
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/ingestion/pipeline.py", line 4, in <module>
    from .nodes import ingestion_heart
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/ingestion/nodes.py", line 10, in <module>
    from great_expectations.core import ExpectationSuite, ExpectationConfiguration
ModuleNotFoundError: No module named 'great_expectations'

  warnings.warn(

2025-06-24 21:41:06,152 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py:452: UserWarning: An error occurred while importing the 'mlopsproject.pipelines.data_unit_tests' module. Nothing defined therein will be returned by 'find_pipelines'.

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py", line 444, in find_pipelines
    pipeline_module = importlib.import_module(pipeline_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/data_unit_tests/__init__.py", line 1, in <module>
    from .pipeline import create_pipeline
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/data_unit_tests/pipeline.py", line 4, in <module>
    from .nodes import test_heart_data
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/data_unit_tests/nodes.py", line 4, in <module>
    from great_expectations.core import ExpectationSuite, ExpectationConfiguration
ModuleNotFoundError: No module named 'great_expectations'

  warnings.warn(

2025-06-24 21:41:06,786 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/io/core.py:575: UserWarning: Since kedro-datasets 2.0, 'Dataset' is spelled with a lowercase 's'. Got 'pandas.ParquetDataSet'.
  warnings.warn(

2025-06-24 21:41:06,788 - kedro_telemetry.plugin - INFO - Kedro is sending anonymous usage data with the sole purpose of improving the product. No personal data or IP addresses are stored on our side. If you want to opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment variables, or create a `.telemetry` file in the current working directory with the contents `consent: false`. Read more at https://docs.kedro.org/en/stable/configuration/telemetry.html
2025-06-24 21:41:24,499 - kedro.framework.project - INFO - Using 'conf/logging.yml' as logging configuration. You can change this by setting the KEDRO_LOGGING_CONFIG environment variable accordingly.
2025-06-24 21:41:24,665 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/cli/utils.py:111: KedroDeprecationWarning: DeprecationWarning: 'kedro run' flag '--namespace' is deprecated and will be replaced with '--namespaces' from Kedro 1.0.0 to allow running multiple namespaces. 
  warnings.warn(message, KedroDeprecationWarning)

2025-06-24 21:41:24,699 - kedro.framework.session.session - INFO - Kedro project MLopsProject
2025-06-24 21:41:25,163 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py:452: UserWarning: An error occurred while importing the 'mlopsproject.pipelines.ingestion' module. Nothing defined therein will be returned by 'find_pipelines'.

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py", line 444, in find_pipelines
    pipeline_module = importlib.import_module(pipeline_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/ingestion/__init__.py", line 1, in <module>
    from .pipeline import create_pipeline
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/ingestion/pipeline.py", line 4, in <module>
    from .nodes import ingestion_heart
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/ingestion/nodes.py", line 10, in <module>
    from great_expectations.core import ExpectationSuite, ExpectationConfiguration
ModuleNotFoundError: No module named 'great_expectations'

  warnings.warn(

2025-06-24 21:41:25,168 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py:452: UserWarning: An error occurred while importing the 'mlopsproject.pipelines.data_unit_tests' module. Nothing defined therein will be returned by 'find_pipelines'.

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py", line 444, in find_pipelines
    pipeline_module = importlib.import_module(pipeline_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/data_unit_tests/__init__.py", line 1, in <module>
    from .pipeline import create_pipeline
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/data_unit_tests/pipeline.py", line 4, in <module>
    from .nodes import test_heart_data
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/data_unit_tests/nodes.py", line 4, in <module>
    from great_expectations.core import ExpectationSuite, ExpectationConfiguration
ModuleNotFoundError: No module named 'great_expectations'

  warnings.warn(

2025-06-24 21:41:25,803 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/io/core.py:575: UserWarning: Since kedro-datasets 2.0, 'Dataset' is spelled with a lowercase 's'. Got 'pandas.ParquetDataSet'.
  warnings.warn(

2025-06-24 21:41:25,805 - kedro_telemetry.plugin - INFO - Kedro is sending anonymous usage data with the sole purpose of improving the product. No personal data or IP addresses are stored on our side. If you want to opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment variables, or create a `.telemetry` file in the current working directory with the contents `consent: false`. Read more at https://docs.kedro.org/en/stable/configuration/telemetry.html
2025-06-24 21:42:56,212 - kedro.framework.project - INFO - Using 'conf/logging.yml' as logging configuration. You can change this by setting the KEDRO_LOGGING_CONFIG environment variable accordingly.
2025-06-24 21:42:56,378 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/cli/utils.py:111: KedroDeprecationWarning: DeprecationWarning: 'kedro run' flag '--namespace' is deprecated and will be replaced with '--namespaces' from Kedro 1.0.0 to allow running multiple namespaces. 
  warnings.warn(message, KedroDeprecationWarning)

2025-06-24 21:42:56,402 - kedro.framework.session.session - INFO - Kedro project MLopsProject
2025-06-24 21:42:56,882 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py:452: UserWarning: An error occurred while importing the 'mlopsproject.pipelines.ingestion' module. Nothing defined therein will be returned by 'find_pipelines'.

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py", line 444, in find_pipelines
    pipeline_module = importlib.import_module(pipeline_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/ingestion/__init__.py", line 1, in <module>
    from .pipeline import create_pipeline
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/ingestion/pipeline.py", line 4, in <module>
    from .nodes import ingestion_heart
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/ingestion/nodes.py", line 10, in <module>
    from great_expectations.core import ExpectationSuite, ExpectationConfiguration
ModuleNotFoundError: No module named 'great_expectations'

  warnings.warn(

2025-06-24 21:42:56,886 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py:452: UserWarning: An error occurred while importing the 'mlopsproject.pipelines.data_unit_tests' module. Nothing defined therein will be returned by 'find_pipelines'.

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py", line 444, in find_pipelines
    pipeline_module = importlib.import_module(pipeline_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/data_unit_tests/__init__.py", line 1, in <module>
    from .pipeline import create_pipeline
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/data_unit_tests/pipeline.py", line 4, in <module>
    from .nodes import test_heart_data
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/data_unit_tests/nodes.py", line 4, in <module>
    from great_expectations.core import ExpectationSuite, ExpectationConfiguration
ModuleNotFoundError: No module named 'great_expectations'

  warnings.warn(

2025-06-24 21:42:57,482 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/io/core.py:575: UserWarning: Since kedro-datasets 2.0, 'Dataset' is spelled with a lowercase 's'. Got 'pandas.CSVDataSet'.
  warnings.warn(

2025-06-24 21:42:57,484 - kedro_telemetry.plugin - INFO - Kedro is sending anonymous usage data with the sole purpose of improving the product. No personal data or IP addresses are stored on our side. If you want to opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment variables, or create a `.telemetry` file in the current working directory with the contents `consent: false`. Read more at https://docs.kedro.org/en/stable/configuration/telemetry.html
2025-06-24 21:43:42,435 - kedro.framework.project - INFO - Using 'conf/logging.yml' as logging configuration. You can change this by setting the KEDRO_LOGGING_CONFIG environment variable accordingly.
2025-06-24 21:43:42,594 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/cli/utils.py:111: KedroDeprecationWarning: DeprecationWarning: 'kedro run' flag '--namespace' is deprecated and will be replaced with '--namespaces' from Kedro 1.0.0 to allow running multiple namespaces. 
  warnings.warn(message, KedroDeprecationWarning)

2025-06-24 21:43:42,617 - kedro.framework.session.session - INFO - Kedro project MLopsProject
2025-06-24 21:43:43,072 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py:452: UserWarning: An error occurred while importing the 'mlopsproject.pipelines.ingestion' module. Nothing defined therein will be returned by 'find_pipelines'.

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py", line 444, in find_pipelines
    pipeline_module = importlib.import_module(pipeline_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/ingestion/__init__.py", line 1, in <module>
    from .pipeline import create_pipeline
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/ingestion/pipeline.py", line 4, in <module>
    from .nodes import ingestion_heart
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/ingestion/nodes.py", line 10, in <module>
    from great_expectations.core import ExpectationSuite, ExpectationConfiguration
ModuleNotFoundError: No module named 'great_expectations'

  warnings.warn(

2025-06-24 21:43:43,077 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py:452: UserWarning: An error occurred while importing the 'mlopsproject.pipelines.data_unit_tests' module. Nothing defined therein will be returned by 'find_pipelines'.

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py", line 444, in find_pipelines
    pipeline_module = importlib.import_module(pipeline_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/data_unit_tests/__init__.py", line 1, in <module>
    from .pipeline import create_pipeline
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/data_unit_tests/pipeline.py", line 4, in <module>
    from .nodes import test_heart_data
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/data_unit_tests/nodes.py", line 4, in <module>
    from great_expectations.core import ExpectationSuite, ExpectationConfiguration
ModuleNotFoundError: No module named 'great_expectations'

  warnings.warn(

2025-06-24 21:43:43,685 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/io/core.py:575: UserWarning: Since kedro-datasets 2.0, 'Dataset' is spelled with a lowercase 's'. Got 'pandas.CSVDataSet'.
  warnings.warn(

2025-06-24 21:43:43,688 - kedro_telemetry.plugin - INFO - Kedro is sending anonymous usage data with the sole purpose of improving the product. No personal data or IP addresses are stored on our side. If you want to opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment variables, or create a `.telemetry` file in the current working directory with the contents `consent: false`. Read more at https://docs.kedro.org/en/stable/configuration/telemetry.html
2025-06-24 21:46:14,483 - kedro.framework.project - INFO - Using 'conf/logging.yml' as logging configuration. You can change this by setting the KEDRO_LOGGING_CONFIG environment variable accordingly.
2025-06-24 21:46:14,676 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/cli/utils.py:111: KedroDeprecationWarning: DeprecationWarning: 'kedro run' flag '--namespace' is deprecated and will be replaced with '--namespaces' from Kedro 1.0.0 to allow running multiple namespaces. 
  warnings.warn(message, KedroDeprecationWarning)

2025-06-24 21:46:14,708 - kedro.framework.session.session - INFO - Kedro project MLopsProject
2025-06-24 21:46:15,249 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py:452: UserWarning: An error occurred while importing the 'mlopsproject.pipelines.ingestion' module. Nothing defined therein will be returned by 'find_pipelines'.

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py", line 444, in find_pipelines
    pipeline_module = importlib.import_module(pipeline_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/ingestion/__init__.py", line 1, in <module>
    from .pipeline import create_pipeline
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/ingestion/pipeline.py", line 4, in <module>
    from .nodes import ingestion_heart
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/ingestion/nodes.py", line 10, in <module>
    from great_expectations.core import ExpectationSuite, ExpectationConfiguration
ModuleNotFoundError: No module named 'great_expectations'

  warnings.warn(

2025-06-24 21:46:15,254 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py:452: UserWarning: An error occurred while importing the 'mlopsproject.pipelines.data_unit_tests' module. Nothing defined therein will be returned by 'find_pipelines'.

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py", line 444, in find_pipelines
    pipeline_module = importlib.import_module(pipeline_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/data_unit_tests/__init__.py", line 1, in <module>
    from .pipeline import create_pipeline
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/data_unit_tests/pipeline.py", line 4, in <module>
    from .nodes import test_heart_data
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/data_unit_tests/nodes.py", line 4, in <module>
    from great_expectations.core import ExpectationSuite, ExpectationConfiguration
ModuleNotFoundError: No module named 'great_expectations'

  warnings.warn(

2025-06-24 21:46:16,003 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/io/core.py:575: UserWarning: Since kedro-datasets 2.0, 'Dataset' is spelled with a lowercase 's'. Got 'pandas.CSVDataSet'.
  warnings.warn(

2025-06-24 21:46:16,006 - kedro_telemetry.plugin - INFO - Kedro is sending anonymous usage data with the sole purpose of improving the product. No personal data or IP addresses are stored on our side. If you want to opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment variables, or create a `.telemetry` file in the current working directory with the contents `consent: false`. Read more at https://docs.kedro.org/en/stable/configuration/telemetry.html
2025-06-24 21:46:45,342 - kedro.framework.project - INFO - Using 'conf/logging.yml' as logging configuration. You can change this by setting the KEDRO_LOGGING_CONFIG environment variable accordingly.
2025-06-24 21:46:45,493 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/cli/utils.py:111: KedroDeprecationWarning: DeprecationWarning: 'kedro run' flag '--namespace' is deprecated and will be replaced with '--namespaces' from Kedro 1.0.0 to allow running multiple namespaces. 
  warnings.warn(message, KedroDeprecationWarning)

2025-06-24 21:46:45,518 - kedro.framework.session.session - INFO - Kedro project MLopsProject
2025-06-24 21:46:45,876 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py:452: UserWarning: An error occurred while importing the 'mlopsproject.pipelines.ingestion' module. Nothing defined therein will be returned by 'find_pipelines'.

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py", line 444, in find_pipelines
    pipeline_module = importlib.import_module(pipeline_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/ingestion/__init__.py", line 1, in <module>
    from .pipeline import create_pipeline
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/ingestion/pipeline.py", line 4, in <module>
    from .nodes import ingestion_heart
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/ingestion/nodes.py", line 10, in <module>
    from great_expectations.core import ExpectationSuite, ExpectationConfiguration
ModuleNotFoundError: No module named 'great_expectations'

  warnings.warn(

2025-06-24 21:46:45,881 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py:452: UserWarning: An error occurred while importing the 'mlopsproject.pipelines.data_unit_tests' module. Nothing defined therein will be returned by 'find_pipelines'.

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py", line 444, in find_pipelines
    pipeline_module = importlib.import_module(pipeline_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/data_unit_tests/__init__.py", line 1, in <module>
    from .pipeline import create_pipeline
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/data_unit_tests/pipeline.py", line 4, in <module>
    from .nodes import test_heart_data
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/data_unit_tests/nodes.py", line 4, in <module>
    from great_expectations.core import ExpectationSuite, ExpectationConfiguration
ModuleNotFoundError: No module named 'great_expectations'

  warnings.warn(

2025-06-24 21:46:46,394 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/io/core.py:575: UserWarning: Since kedro-datasets 2.0, 'Dataset' is spelled with a lowercase 's'. Got 'pandas.CSVDataSet'.
  warnings.warn(

2025-06-24 21:46:46,396 - kedro_telemetry.plugin - INFO - Kedro is sending anonymous usage data with the sole purpose of improving the product. No personal data or IP addresses are stored on our side. If you want to opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment variables, or create a `.telemetry` file in the current working directory with the contents `consent: false`. Read more at https://docs.kedro.org/en/stable/configuration/telemetry.html
2025-06-24 21:48:24,108 - kedro.framework.project - INFO - Using 'conf/logging.yml' as logging configuration. You can change this by setting the KEDRO_LOGGING_CONFIG environment variable accordingly.
2025-06-24 21:48:24,272 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/cli/utils.py:111: KedroDeprecationWarning: DeprecationWarning: 'kedro run' flag '--namespace' is deprecated and will be replaced with '--namespaces' from Kedro 1.0.0 to allow running multiple namespaces. 
  warnings.warn(message, KedroDeprecationWarning)

2025-06-24 21:48:24,306 - kedro.framework.session.session - INFO - Kedro project MLopsProject
2025-06-24 21:48:24,796 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py:452: UserWarning: An error occurred while importing the 'mlopsproject.pipelines.ingestion' module. Nothing defined therein will be returned by 'find_pipelines'.

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py", line 444, in find_pipelines
    pipeline_module = importlib.import_module(pipeline_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/ingestion/__init__.py", line 1, in <module>
    from .pipeline import create_pipeline
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/ingestion/pipeline.py", line 4, in <module>
    from .nodes import ingestion_heart
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/ingestion/nodes.py", line 10, in <module>
    from great_expectations.core import ExpectationSuite, ExpectationConfiguration
ModuleNotFoundError: No module named 'great_expectations'

  warnings.warn(

2025-06-24 21:48:24,802 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py:452: UserWarning: An error occurred while importing the 'mlopsproject.pipelines.data_unit_tests' module. Nothing defined therein will be returned by 'find_pipelines'.

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/framework/project/__init__.py", line 444, in find_pipelines
    pipeline_module = importlib.import_module(pipeline_module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/data_unit_tests/__init__.py", line 1, in <module>
    from .pipeline import create_pipeline
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/data_unit_tests/pipeline.py", line 4, in <module>
    from .nodes import test_heart_data
  File "/Users/nunonunes/Documents/GitHub/MLopsProject/src/mlopsproject/pipelines/data_unit_tests/nodes.py", line 4, in <module>
    from great_expectations.core import ExpectationSuite, ExpectationConfiguration
ModuleNotFoundError: No module named 'great_expectations'

  warnings.warn(

2025-06-24 21:48:25,406 - py.warnings - WARNING - /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kedro/io/core.py:575: UserWarning: Since kedro-datasets 2.0, 'Dataset' is spelled with a lowercase 's'. Got 'pandas.CSVDataSet'.
  warnings.warn(

2025-06-24 21:48:25,409 - kedro_telemetry.plugin - INFO - Kedro is sending anonymous usage data with the sole purpose of improving the product. No personal data or IP addresses are stored on our side. If you want to opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment variables, or create a `.telemetry` file in the current working directory with the contents `consent: false`. Read more at https://docs.kedro.org/en/stable/configuration/telemetry.html
